# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc ""
  homepage "https://github.com/bricktopab/homebrew-gg"
  version "0.0.3"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/bricktopab/gg/releases/download/0.0.3/gg_Darwin_x86_64.tar.gz"
      sha256 "f479e19a2e467b56ba5090f4af236eb6796a075cfddbddf1a578b86b2ecdb6d4"

      def install
        bin.install "gg"
      end
    end
    on_arm do
      url "https://github.com/bricktopab/gg/releases/download/0.0.3/gg_Darwin_arm64.tar.gz"
      sha256 "2387b07270baccc8c0f9de1085ff241ff54bc2abe48507abeed1f7c86a8eea48"

      def install
        bin.install "gg"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bricktopab/gg/releases/download/0.0.3/gg_Linux_x86_64.tar.gz"
        sha256 "dd3310eef31d9eae88884771101dec69a15700a2a668c2f35bfb433b5684735b"

        def install
          bin.install "gg"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bricktopab/gg/releases/download/0.0.3/gg_Linux_arm64.tar.gz"
        sha256 "1a489db8d831266cede0f2201c9791fd16de49f20de0d61b32655d3f491dbf7b"

        def install
          bin.install "gg"
        end
      end
    end
  end

  def post_install
    puts "Greetings from gg!"
    puts "If you are using zsh, you may need to unset an alias coming from ~/.oh-my-zsh/plugins/git/git.plugin.zsh: "
    puts "test ~/.zshrc && echo 'unalias gg' >>~/.zshrc"
  end
end
