# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gg < Formula
  desc ""
  homepage "https://github.com/bricktopab/homebrew-gg"
  version "0.0.2"

  depends_on "git"

  on_macos do
    on_intel do
      url "https://github.com/bricktopab/gg/releases/download/0.0.2/gg_Darwin_x86_64.tar.gz"
      sha256 "d69d0989b6722f599810730ca55a78d121b7d4c68b143e29f9205284d9d72ecc"

      def install
        bin.install "gg"
      end
    end
    on_arm do
      url "https://github.com/bricktopab/gg/releases/download/0.0.2/gg_Darwin_arm64.tar.gz"
      sha256 "7c5860836b5e1947862c0c1254cce28ecc7f6bb92bffbc62556156cfcb11c260"

      def install
        bin.install "gg"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bricktopab/gg/releases/download/0.0.2/gg_Linux_x86_64.tar.gz"
        sha256 "0e5df766e43672206aed9518f0cc562e3f8ba45d2db75d839c8958ecf8e0afd5"

        def install
          bin.install "gg"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bricktopab/gg/releases/download/0.0.2/gg_Linux_arm64.tar.gz"
        sha256 "c219e843ce1dcb7a4ff170ceac1f82c3f86a59c7d701d66d545e128b3913a305"

        def install
          bin.install "gg"
        end
      end
    end
  end

  def post_install
    system 'test ~/.zshrc && echo "unalias gg" >> ~/.zshrc'
  end
end
